import StyleDictionary from "style-dictionary";

const getTokensByMode = (tokens, mode) =>
  tokens.filter((token) => token.path[token.path.length - 1] === mode);

const THEME_NAMES = ["default", "dark", "muted", "dark-high-contrast"];
const TOKEN_MODES = new Set(THEME_NAMES);
const GENERATED_HEADER =
  "// Generated by Style Dictionary. Do not edit directly.\n\n";

const getTransformedValue = (token) =>
  token.$value ??
  token.value ??
  token.original?.$value ??
  token.original?.value;

const getSourceValue = (token) =>
  token.original?.$value ?? token.original?.value ?? getTransformedValue(token);

const sortRecord = (record) =>
  Object.fromEntries(
    Object.entries(record).sort(([left], [right]) => left.localeCompare(right)),
  );

const formatConstant = (name, value) =>
  `export const ${name} = ${JSON.stringify(value, null, 2)} as const;`;

const toCssVariableReference = (value) => {
  if (typeof value !== "string") return undefined;

  const match = value.match(/^\{([^}]+)\}$/);
  if (!match) return undefined;

  const path = match[1].split(".");
  const lastSegment = path[path.length - 1];
  const tokenName = TOKEN_MODES.has(lastSegment)
    ? path[path.length - 2]
    : lastSegment;

  return tokenName ? `var(--fs-${tokenName})` : undefined;
};

const CATEGORY_METADATA = {
  "fs-colors/FS-Primitive-Colors": {
    label: "Colors/Primitives",
    presenter: "Color",
  },
  "fs-colors/FS-Primitive-Colors-extended": {
    label: "Colors/Extended",
    presenter: "Color",
  },
  "fs-colors/FS-Semantic-Colors/Surface": {
    label: "Colors/Surface",
    presenter: "Color",
  },
  "fs-colors/FS-Semantic-Colors/Content": {
    label: "Colors/Content",
    presenter: "Color",
  },
  "fs-colors/FS-Semantic-Colors/Action": {
    label: "Colors/Actions",
    presenter: "Color",
  },
  "fs-colors/FS-Semantic-Colors/Feedback": {
    label: "Colors/Feedback",
    presenter: "Color",
  },
  "fs-colors/FS-Semantic-Colors/Borders": {
    label: "Borders",
    presenter: "Border",
  },
  "fs-game/Game-Colors": {
    label: "Game/Colors",
    presenter: "Color",
  },
  "fs-spacing/Spacing": {
    label: "Spacing Scale",
    presenter: "Spacing",
  },
  "fs-typography/FontFamilies": {
    label: "Typography/Families",
    presenter: "FontFamily",
  },
  "fs-typography/FontSizes": {
    label: "Typography/Sizes",
    presenter: "FontSize",
  },
  "fs-typography/FontWeights": {
    label: "Typography/Weights",
    presenter: "FontWeight",
  },
  "fs-typography/LineHeights": {
    label: "Typography/Line Heights",
    presenter: "LineHeight",
  },
  "fs-motion/Durations": {
    label: "Motion/Durations",
    presenter: "Duration",
  },
  "fs-motion/Easings": {
    label: "Motion/Easings",
    presenter: "CubicBezier",
  },
};

const buildThemeBlock = (selector, tokens) => {
  const lines = tokens.map((token) => {
    const baseName = token.path[token.path.length - 2];
    const originalValue = token.original?.$value ?? token.original?.value;
    // Preserve aliases as CSS-variable references; keep existing literal output stable.
    const value =
      toCssVariableReference(originalValue) ??
      (token.value !== undefined ? token.value : originalValue);
    const groupKey = token.path.slice(0, token.path.length - 2).join("/");

    return {
      baseName,
      value,
      groupKey,
    };
  });

  const seenGroups = new Set();
  const outputLines = [];

  lines.forEach(({ baseName, value, groupKey }) => {
    if (!seenGroups.has(groupKey)) {
      const meta = CATEGORY_METADATA[groupKey];
      if (meta) {
        outputLines.push(`  /* @tokens ${meta.label} */`);
        if (meta.presenter) {
          outputLines.push(`  /* @presenter ${meta.presenter} */`);
        }
      }
      seenGroups.add(groupKey);
    }

    outputLines.push(`  --fs-${baseName}: ${value};`);
  });

  const body = outputLines.join("\n");
  const content = body ? `\n${body}\n` : "\n";

  return `${selector} {${content}}\n\n`;
};

StyleDictionary.registerFormat({
  name: "css/variablesByTheme",
  format: ({ dictionary }) => {
    const defaultTokens = getTokensByMode(dictionary.allTokens, "default");
    const darkTokens = getTokensByMode(dictionary.allTokens, "dark");
    const mutedTokens = getTokensByMode(dictionary.allTokens, "muted");
    const highContrastTokens = getTokensByMode(
      dictionary.allTokens,
      "dark-high-contrast",
    );

    let output = buildThemeBlock(":root", defaultTokens);
    output += buildThemeBlock('[data-theme="dark"]', darkTokens);
    output += buildThemeBlock('[data-theme="muted"]', mutedTokens);
    output += buildThemeBlock(
      '[data-theme="dark-high-contrast"]',
      highContrastTokens,
    );

    return output.trimEnd();
  },
});

StyleDictionary.registerFormat({
  name: "typescript/colorsByTheme",
  format: ({ dictionary }) => {
    const colors = Object.fromEntries(
      THEME_NAMES.map((theme) => {
        const layers = {
          primitive: {},
          semantic: {},
          game: {},
        };

        getTokensByMode(dictionary.allTokens, theme)
          .filter(
            (token) =>
              token.path[0] === "fs-colors" || token.path[0] === "fs-game",
          )
          .forEach((token) => {
            const baseName = token.path[token.path.length - 2];
            const isGameToken = token.path[0] === "fs-game";
            const isSemanticToken = token.path.includes("FS-Semantic-Colors");
            const layer = isGameToken
              ? "game"
              : isSemanticToken
                ? "semantic"
                : "primitive";
            const tokenName = isGameToken
              ? baseName.replace(/^color-game-/, "")
              : baseName.replace(/^color-/, "");

            layers[layer][tokenName] = getTransformedValue(token);
          });

        return [
          theme,
          {
            primitive: sortRecord(layers.primitive),
            semantic: sortRecord(layers.semantic),
            game: sortRecord(layers.game),
          },
        ];
      }),
    );

    return (
      [
        GENERATED_HEADER.trimEnd(),
        formatConstant("colors", colors),
        "export type ColorThemeName = keyof typeof colors;",
        "export type PrimitiveColorToken = keyof typeof colors.default.primitive;",
        "export type SemanticColorToken = keyof typeof colors.default.semantic;",
        "export type GameColorToken = keyof typeof colors.default.game;",
      ].join("\n\n") + "\n"
    );
  },
});

StyleDictionary.registerFormat({
  name: "typescript/motion",
  format: ({ dictionary }) => {
    const motion = {
      duration: {},
      easing: {},
      spring: {},
    };

    getTokensByMode(dictionary.allTokens, "default")
      .filter((token) => token.path[0] === "fs-motion")
      .forEach((token) => {
        const groupName = token.path[1];
        const baseName = token.path[token.path.length - 2];
        const group =
          groupName === "Durations"
            ? "duration"
            : groupName === "Easings"
              ? "easing"
              : groupName === "Springs"
                ? "spring"
                : undefined;

        if (!group) return;

        const prefix =
          group === "easing"
            ? baseName.startsWith("motion-easing-")
              ? "motion-easing-"
              : "motion-ease-"
            : `motion-${group}-`;

        motion[group][baseName.replace(prefix, "")] = getSourceValue(token);
      });

    const sortedMotion = {
      duration: sortRecord(motion.duration),
      easing: sortRecord(motion.easing),
      spring: sortRecord(motion.spring),
    };

    return (
      [
        GENERATED_HEADER.trimEnd(),
        formatConstant("motion", sortedMotion),
        "export type MotionDurationToken = keyof typeof motion.duration;",
        "export type MotionEasingToken = keyof typeof motion.easing;",
        "export type MotionSpringToken = keyof typeof motion.spring;",
      ].join("\n\n") + "\n"
    );
  },
});

StyleDictionary.registerFormat({
  name: "typescript/themes",
  format: () =>
    [
      GENERATED_HEADER.trimEnd(),
      formatConstant("themes", THEME_NAMES),
      'export const defaultTheme: ThemeName = "default";',
      "export type ThemeName = (typeof themes)[number];",
    ].join("\n\n") + "\n",
});

const config = {
  source: [
    "tokens/fs.tokens.json",
    "tokens/fs.motion.tokens.json",
    "tokens/fs.game.tokens.json",
  ],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "styles/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variablesByTheme",
        },
      ],
    },
    typescript: {
      transformGroup: "js",
      buildPath: "common/generated/",
      files: [
        {
          destination: "colors.ts",
          format: "typescript/colorsByTheme",
        },
        {
          destination: "motion.ts",
          format: "typescript/motion",
        },
        {
          destination: "themes.ts",
          format: "typescript/themes",
        },
      ],
    },
  },
};

export default config;
