import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import { workSans, spaceGrotesk } from "./fonts";
import { ServiceProvider } from "@/application/providers/ServiceProvider";
import { createServices } from "@/infrastructure/services/createServices";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const services = createServices();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${workSans.variable} ${spaceGrotesk.variable}`}
    >
      <body className="antialiased">
        <Script
          id="theme-script"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var applyTheme = function(theme) {
                    if (theme && theme !== 'default') {
                      document.documentElement.setAttribute('data-theme', theme);
                    } else {
                      document.documentElement.removeAttribute('data-theme');
                    }
                  };

                  var getSystemTheme = function() {
                    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                      return 'dark';
                    }
                    return 'default';
                  };

                  var storedTheme = localStorage.getItem('theme');

                  if (!storedTheme) {
                    storedTheme = 'system';
                    localStorage.setItem('theme', 'system');
                  }

                  var prefersDark = window.matchMedia ? window.matchMedia('(prefers-color-scheme: dark)') : null;
                  var applyStoredTheme = function(theme) {
                    if (theme === 'system') {
                      applyTheme(getSystemTheme());
                    } else {
                      applyTheme(theme);
                    }
                  };

                  applyStoredTheme(storedTheme);

                  if (prefersDark) {
                    var listener = function(event) {
                      if (localStorage.getItem('theme') === 'system') {
                        applyTheme(event.matches ? 'dark' : 'default');
                      }
                    };
                    if (typeof prefersDark.addEventListener === 'function') {
                      prefersDark.addEventListener('change', listener);
                    } else if (typeof prefersDark.addListener === 'function') {
                      prefersDark.addListener(listener);
                    }
                  }
                } catch (error) {
                  if (process.env.NODE_ENV !== "production") {
                    console.error("Theme initialization failed", error);
                  }
                }
              })();
            `,
          }}
        />
        <ServiceProvider services={services}>{children}</ServiceProvider>
      </body>
    </html>
  );
}
