// Authoring only (macOS/CoreText). Production builds consume the checked-in paths.
// Usage: swift scripts/export-web-aperture.swift <repository-root> <output-root>
import Foundation
import CoreText
import CoreGraphics

let root = URL(fileURLWithPath: CommandLine.arguments[1])
let output = URL(fileURLWithPath: CommandLine.arguments[2])
let fontURL = root.appendingPathComponent("frontend/public/fonts/Work_Sans/WorkSans-VariableFont_wght.ttf")
let descriptors = CTFontManagerCreateFontDescriptorsFromURL(fontURL as CFURL) as! [CTFontDescriptor]
let descriptor = CTFontDescriptorCreateCopyWithAttributes(descriptors[0], [
    kCTFontVariationAttribute: [NSNumber(value: 0x77676874): NSNumber(value: 900)]
] as CFDictionary)
let font = CTFontCreateWithFontDescriptor(descriptor, 1000, nil)
guard CTFontCopyFamilyName(font) as String == "Work Sans" else { fatalError("Unexpected font substitution") }
let line = CTLineCreateWithAttributedString(NSAttributedString(string: "WEB", attributes: [NSAttributedString.Key(kCTFontAttributeName as String): font]))
let outline = CGMutablePath()
for run in CTLineGetGlyphRuns(line) as! [CTRun] {
    let count = CTRunGetGlyphCount(run)
    var glyphs = [CGGlyph](repeating: 0, count: count)
    var positions = [CGPoint](repeating: .zero, count: count)
    CTRunGetGlyphs(run, CFRange(location: 0, length: 0), &glyphs)
    CTRunGetPositions(run, CFRange(location: 0, length: 0), &positions)
    for index in 0..<count {
        guard let path = CTFontCreatePathForGlyph(font, glyphs[index], nil) else { fatalError("Missing outline") }
        outline.addPath(path, transform: CGAffineTransform(translationX: positions[index].x, y: positions[index].y))
    }
}
let bounds = outline.boundingBoxOfPath
func number(_ value: CGFloat) -> String {
    let value = abs(value) < 0.0005 ? 0 : value
    return String(format: "%.3f", locale: Locale(identifier: "en_US_POSIX"), Double(value)).replacingOccurrences(of: #"\.?0+$"#, with: "", options: .regularExpression)
}
func point(_ p: CGPoint) -> String { "\(number(p.x - bounds.minX)) \(number(bounds.maxY - p.y))" }
var commands: [String] = []
outline.applyWithBlock { pointer in
    let e = pointer.pointee
    switch e.type {
    case .moveToPoint: commands.append("M" + point(e.points[0]))
    case .addLineToPoint: commands.append("L" + point(e.points[0]))
    case .addQuadCurveToPoint: commands.append("Q" + point(e.points[0]) + " " + point(e.points[1]))
    case .addCurveToPoint: commands.append("C" + point(e.points[0]) + " " + point(e.points[1]) + " " + point(e.points[2]))
    case .closeSubpath: commands.append("Z")
    @unknown default: fatalError("Unknown outline operation")
    }
}
let path = commands.joined(separator: " ")
let box = "0 0 \(number(bounds.width)) \(number(bounds.height))"
let svg = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"\(box)\"><path fill=\"#000000\" fill-rule=\"nonzero\" d=\"\(path)\"/></svg>\n"
let data = "// Generated by scripts/export-web-aperture.swift from bundled Work Sans, weight 900.\n// Shared trusted geometry keeps the mask-independent fallback identical to the SVG.\nexport const webViewBox = \"\(box)\";\nexport const webPath = \"\(path)\";\n"
for (relative, contents) in [("frontend/public/scene-apertures/web-work-sans.svg", svg), ("frontend/data/webApertureGeometry.ts", data)] {
    let url = output.appendingPathComponent(relative)
    try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
    try contents.write(to: url, atomically: true, encoding: .utf8)
}
print("Font: \(CTFontCopyPostScriptName(font)); variation: \(String(describing: CTFontCopyVariation(font))); viewBox: \(box)")
